# Generated by Django 3.2.24 on 2024-03-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_per_kg',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
